import pkg.*;
import java.util.Scanner;
import java.util.Random;


class starter {
	public static void main(String args[]) {
		// Your code goes below here
	Random rand = new Random();
	System.out.println("These are the twenty numbers.");
	int[] one = new int[20];
	int a = 1+ rand.nextInt(50);
	one[0] =a;
	int b = 1+ rand.nextInt(50);
	one[1]=b;
	int c = 1+ rand.nextInt(50);
	one[2]=c;
	int d = 1+ rand.nextInt(50);
	one[3]=d;
	int e = 1+ rand.nextInt(50);
	one[4]=e;
	int f = 1+ rand.nextInt(50);
	one[5]=f;
	int g = 1+ rand.nextInt(50);
	one[6]=g;
	int h = 1+ rand.nextInt(50);
	one[7]=h;
	int i = 1+ rand.nextInt(50);
	one[8]=i;
	int j = 1+ rand.nextInt(50);
	one[9]=j;
	int k = 1+ rand.nextInt(50);
	one[10]=k;
	int l = 1+ rand.nextInt(50);
	one[11]=l;
	int m = 1+ rand.nextInt(50);
	one[12]=m;
	int n = 1+ rand.nextInt(50);
	one[13]=n;
	int o = 1+ rand.nextInt(50);
	one[14]=o;
	int p = 1+ rand.nextInt(50);
	one[15]=p;
	int q = 1+ rand.nextInt(50);
	one[16]=q;
	int r = 1+ rand.nextInt(50);
	one[17]=r;
	int s = 1+ rand.nextInt(50);
	one[18]=s;
	int t = 1+ rand.nextInt(50);
	one[19]=t;
	System.out.print(one[0]+ " ");
	System.out.print(one[1]+ " ");
	System.out.print(one[2]+ " ");
	System.out.print(one[3]+ " ");
	System.out.print(one[4]+ " ");
	System.out.print(one[5]+ " ");
	System.out.print(one[6]+ " ");
	System.out.print(one[7]+ " ");
	System.out.print(one[8]+ " ");
	System.out.print(one[9]+ " ");
	System.out.print(one[10]+ " ");
	System.out.print(one[11]+ " ");
	System.out.print(one[12]+ " ");
	System.out.print(one[13]+ " ");
	System.out.print(one[14]+ " ");
	System.out.print(one[15]+ " ");
	System.out.print(one[16]+ " ");
	System.out.print(one[17]+ " ");
	System.out.print(one[18]+ " ");
	System.out.println(one[19]+ " ");
	
	int[] two = new int[20];
	two[19] =a;
	two[18]=b;
	two[17]=c;
	two[16]=d;
	two[15]=e;
	two[14]=f;
	two[13]=g;
	two[12]=h;
	two[11]=i;
	two[10]=j;
	two[9]=k;
	two[8]=l;
	two[7]=m;
	two[6]=n;
	two[5]=o;
	two[4]=p;
	two[3]=q;
	two[2]=r;
	two[1]=s;
	two[0]=t;
	System.out.println("These are the values backward.");
	System.out.print(two[0]+ " ");
	System.out.print(two[1]+ " ");
	System.out.print(two[2]+ " ");
	System.out.print(two[3]+ " ");
	System.out.print(two[4]+ " ");
	System.out.print(two[5]+ " ");
	System.out.print(two[6]+ " ");
	System.out.print(two[7]+ " ");
	System.out.print(two[8]+ " ");
	System.out.print(two[9]+ " ");
	System.out.print(two[10]+ " ");
	System.out.print(two[11]+ " ");
	System.out.print(two[12]+ " ");
	System.out.print(two[13]+ " ");
	System.out.print(two[14]+ " ");
	System.out.print(two[15]+ " ");
	System.out.print(two[16]+ " ");
	System.out.print(two[17]+ " ");
	System.out.print(two[18]+ " ");
	System.out.print(two[19]+ " ");
		
	}
}
